version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build-and-test:
    executor: cypress/base-14
    steps:
      - checkout
      - cypress/install
      - cypress/run:
          yarn: true
          start: npm start

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test

