version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:14
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests (create_po)
          command: npx cypress run --spec "cypress/e2e/purchase_order/create_po.cy.js"
      - run:
          name: Run Cypress Tests (po_table_actions)
          command: npx cypress run --spec "cypress/e2e/purchase_order/po_table_actions.cy.js"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build


