version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
